import React, { useEffect } from 'react';

const TermsAndConditions = () => {
  // Scroll to top on load
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <main style={{ padding: '60px 20px', maxWidth: '900px', margin: '0 auto', fontFamily: 'Inter, sans-serif', color: '#333', lineHeight: '1.8' }}>
      <h1 style={{ fontSize: '36px', color: '#111', marginBottom: '10px', fontFamily: 'Space Grotesk, sans-serif' }}>Terms and Conditions</h1>
      <p style={{ color: '#666', marginBottom: '40px' }}>Last Updated: October 2026</p>

      <section style={{ marginBottom: '30px' }}>
        <h2 style={{ fontSize: '22px', color: '#111', marginTop: '30px', marginBottom: '15px' }}>1. Introduction</h2>
        <p>Welcome to Tickora. By accessing our website, registering an account, or purchasing a ticket, you agree to be bound by these Terms and Conditions. Tickora acts as a platform connecting Event Organizers with Attendees. We do not host, organize, or manage the events listed on our platform.</p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2 style={{ fontSize: '22px', color: '#111', marginTop: '30px', marginBottom: '15px' }}>2. User Roles and Responsibilities</h2>
        <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
          <li style={{ marginBottom: '10px' }}><strong>Attendees:</strong> You agree to provide accurate information when purchasing tickets. Tickets are subject to the specific refund and entry policies set by the Event Organizer.</li>
          <li style={{ marginBottom: '10px' }}><strong>Organizers:</strong> You are solely responsible for ensuring your events comply with all local laws. You must fulfill the event as described on your event page. Misrepresentation or failure to deliver an event may result in account suspension and forfeiture of payouts.</li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2 style={{ fontSize: '22px', color: '#111', marginTop: '30px', marginBottom: '15px' }}>3. Fees, Payments, and Payouts</h2>
        <p><strong>Platform Fees:</strong> Tickora charges a 7% platform fee on all paid ticket sales. This fee is automatically deducted from the gross revenue generated by the event.</p>
        <p><strong>Payouts:</strong> Organizers may request payouts for their available balance via the platform. Payouts are processed to verified Nigerian bank accounts. Tickora reserves the right to withhold payouts if fraudulent activity, chargebacks, or event cancellations are suspected.</p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2 style={{ fontSize: '22px', color: '#111', marginTop: '30px', marginBottom: '15px' }}>4. Refunds and Cancellations</h2>
        <p>Tickora serves only as the payment processor. All refund requests must be directed to the Event Organizer. If an Organizer cancels an event, they are strictly responsible for refunding all Attendees. Tickora platform fees are strictly non-refundable.</p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2 style={{ fontSize: '22px', color: '#111', marginTop: '30px', marginBottom: '15px' }}>5. Limitation of Liability</h2>
        <p>Tickora is not liable for any injury, loss, claim, or damage arising from your attendance at any event booked through our platform. Organizers assume full liability for their events.</p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2 style={{ fontSize: '22px', color: '#111', marginTop: '30px', marginBottom: '15px' }}>6. Account Termination</h2>
        <p>We reserve the right to suspend or terminate accounts that violate these terms, engage in fraudulent transactions, or post illegal/inappropriate event content without prior notice.</p>
      </section>

      <hr style={{ border: 'none', borderTop: '1px solid #eee', margin: '40px 0' }} />
      <p style={{ fontSize: '14px', color: '#777' }}>If you have any questions about these Terms, please contact support@tickora.com.</p>
    </main>
  );
};

export default TermsAndConditions;
